const SZ=20,W=10,H=5,CL='#444861',CF='#7a7a7a',CW='#6b4c35',CD='#8a3323',CK='#2e8b57',CT='gold',CE='red',CP='purple',CO='blue',CS='white';
let s,e,c,p,i=0,tm=0,sc=0,kc=0,tk=0,lv=1,ms=10+Date.now()%5*2,l=3,go=false,wi=false,ks={},mx=0,my=0,pr=true,fu=false,renderLoopId;
let scene,camera,renderer,walls,maze=[],itm=[],doors=[],keys=[],ens=[],traps=[],orbs=[],part=[],gr,wc=0,hc=0;
function gi(a){return document.getElementById(a)}
function ae(t,e,l){t.addEventListener(e,l)}
function IM(){const g=gi('cnv');scene=new THREE.Scene();scene.fog=new THREE.FogExp2(CL,0.015);camera=new THREE.PerspectiveCamera(75,g.clientWidth/g.clientHeight,0.1,1000);renderer=new THREE.WebGLRenderer({canvas:g,antialias:true});renderer.setSize(g.clientWidth,g.clientHeight);renderer.shadowMap.enabled=true;gr=new THREE.Group();scene.add(gr);const al=new THREE.AmbientLight(0x404040,0.6);scene.add(al);const dl=new THREE.DirectionalLight(0xffffff,0.5);dl.position.set(50,100,50);dl.castShadow=true;scene.add(dl);ae(window,'resize',()=>{const a=gi('cnv');camera.aspect=a.clientWidth/a.clientHeight;camera.updateProjectionMatrix();renderer.setSize(a.clientWidth,a.clientHeight)});ae(document,'keydown',z=>{const a=z.key.toLowerCase();ks[a]=true;if(a==='arrowup')ks.w=true;if(a==='arrowdown')ks.s=true;if(a==='arrowleft')ks.a=true;if(a==='arrowright')ks.d=true});ae(document,'keyup',z=>{const a=z.key.toLowerCase();ks[a]=false;if(a==='arrowup')ks.w=false;if(a==='arrowdown')ks.s=false;if(a==='arrowleft')ks.a=false;if(a==='arrowright')ks.d=false});ae(document,'mousemove',z=>{if(!pr)return;mx+=z.movementX*0.002;my=Math.max(-Math.PI/2+0.1,Math.min(Math.PI/2-0.1,my+z.movementY*0.002))});ae(document,'click',()=>{if(!pr&&document.pointerLockElement!==gi('cnv'))gi('cnv').requestPointerLock()});ae(document,'pointerlockchange',()=>{if(!pr)pr=document.pointerLockElement!==gi('cnv')})}
function MX(sx,sy){const m=[];for(let y=0;y<sy;y++){const r=[];for(let x=0;x<sx;x++)r.push({w:true,v:false,x,y});m.push(r)}return m}
function GM(sx,sy){const m=MX(sx,sy),st=[{x:1,y:1}];m[1][1].v=true;while(st.length>0){const c=st[st.length-1];const n=[{x:c.x+2,y:c.y,d:2},{x:c.x-2,y:c.y,d:-2},{x:c.x,y:c.y+2,d:sx*2},{x:c.x,y:c.y-2,d:-sx*2}].filter(a=>a.x>0&&a.x<sx-1&&a!=='#'&&a.y>0&&a.y<sy-1&&!m[a.y][a.x].v);if(n.length>0){const r=n[Math.floor(Math.random()*n.length)];m[(c.y+r.y)/2][(c.x+r.x)/2].w=false;m[r.y][r.x].w=false;m[r.y][r.x].v=true;st.push({x:r.x,y:r.y})}else st.pop()}m[1][1].w=false;m[sky-2][sx-2].w=false;return m}
function PM(){walls=new THREE.Group();const wm=new THREE.MeshPhongMaterial({color:CW});for(let y=0;y<hc;y++)for(let x=0;x<wc;x++)if(maze[y][x].w){const b=new THREE.Mesh(new THREE.BoxGeometry(W,H,W),wm);b.position.set(x*W,0,y*W);b.castShadow=true;b.receiveShadow=true;walls.add(b)}gr.add(walls);const fm=new THREE.MeshPhongMaterial({color:CF});const fg=new THREE.PlaneGeometry(wc*W,hc*W);const f=new THREE.Mesh(fg,fm);f.rotation.x=-Math.PI/2;f.position.set((wc-1)*W/2,-H/2,(hc-1)*W/2);f.receiveShadow=true;gr.add(f);const cm=new THREE.MeshPhongMaterial({color:CL});const cg=new THREE.PlaneGeometry(wc*W,hc*W);const c=new THREE.Mesh(cg,cm);c.rotation.x=Math.PI/2;c.position.set((wc-1)*W/2,H*2,(hc-1)*W/2);gr.add(c);const tm=new THREE.MeshPhongMaterial({color:CT,emissive:0xaa8800,shininess:100});const tg=new THREE.Mesh(new THREE.CylinderGeometry(2,2,8,16),tm);tg.position.set((wc-2)*W,H/2,(hc-2)*W);tg.rotation.z=Math.PI/2;gr.add(tg);const s=new THREE.PointLight(CT,1,15);s.position.copy(tg.position);scene.add(s)}
function CKP(x,y){keys.forEach(k=>{if(!k.c&&Math.abs(x-k.x)<1.5&&Math.abs(y-k.y)<1.5){k.c=true;k.m.visible=false;kc++}})}
function CDP(x,y){let b=false;doors.forEach((d,ix)=>{if(Math.abs(x-d.x)<1.2&&Math.abs(y-d.y)<1.2){if(kc>0){kc--;doors.splice(ix,1);gr.remove(d.m);b=true}else if(!b)showMsg('Need key!')}});return b}
function showMsg(t){const m=gi('msg